sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
env:
  global:
  - secure: 3BXzHYdDU0aCDB88S0JFTgV2Z4prE1j7asKSO8FGrQazvja6Cx0sStfuDa6SRjcAm4BWkP7Feixr6yGqL57ep4UC3Z+BcHvxFBdgfL5FAzdbnuMwEn7DJ11uXZPJampbORLgS8WniVgeRiEcHtZm+z2HHWf5fo0aJXEFEXGYLqU=
matrix:
  include:
  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
    - Rscript -e 'install.packages("SpaDES.core", dependencies = TRUE, repos = "https://cran.rstudio.com")'
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    r_github_packages:
      - jimhester/lintr
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
    - Rscript -e 'install.packages("SpaDES.core", dependencies = TRUE, repos = "https://cran.rstudio.com")'
    after_success:
    - Rscript -e 'covr::coveralls(package_coverage(type = "all", quiet = FALSE)))'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
    - Rscript -e 'install.packages("SpaDES.core", dependencies = TRUE, repos = "https://cran.rstudio.com")'
    r_packages:
    - devtools
  - os: osx
    osx_image: xcode8.2
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    before_script:
    - Rscript -e 'install.packages(c("rgdal", "SpaDES.core"), repos = "https://cran.rstudio.com", type = "source")'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only:
  - master
  - development
  - testing
